version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-20190909e
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python -m pip install -q -U pip
            python -m pip install -q -r requirements/dev.txt
            python -m pip --version
      - save_cache:
          paths:
            - ".venv"
            - ".nox"
            - "~/.cache/pip"
          key: dependencies-20190909e
      - run:
          name: Install into updated environment
          command: |
            . .venv/bin/activate
            python -m pip --version
            python -m pip install -e .
      - run:
          name: Run nox
          command: |
            . .venv/bin/activate
            python -m pip --version
            python -m pip freeze
            nox --noxfile noxfile_circleci.py
            nox
