version: 2.1
workflows:
  do_it_all:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-20190911
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install -q -U pip
            python3 -m pip install -q -r requirements/dev.txt
            python3 -m pip --version
      - save_cache:
          paths:
            - ".venv"
            - "~/.cache/pip"
          key: dependencies-20190911
      - run:
          name: Install into updated environment
          command: |
            . .venv/bin/activate
            python3 -m pip --version
            python3 -m pip install -e .
      - run:
          name: Run nox
          command: |
            . .venv/bin/activate
            python3 -m pip --version
            python3 -m pip freeze
            rm noxfile.py
            nox --noxfile -l
            nox --noxfile
