version: 2.1
workflows:
  ci_testing:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.7
        environment:
          MYPYPATH: "./stubs"
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-20240730b
      - run:
          name: Prepare environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install -q -U pip
            python3 -m pip install -q -r requirements/circleci.txt
            python3 -m pip --version
      - save_cache:
          paths:
            - "~/.cache/pip"
          key: dependencies-20240730b
      - run:
          name: Run the nox gauntlet
          command: |
            . .venv/bin/activate
            python3 -m pip --version
            python3 -m pip freeze
            nox -k test -l
            nox -k test --no-error-on-missing-interpreters --report build/nox-status.json
      - store_test_results:
          path: build/pytest
      - store_artifacts:
          path: build
