version: 2.1
workflows:
  do_it_all:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-20190912f
      - run:
          name: Prepare environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python3 -m pip install -q -U pip
            python3 -m pip install -q -r requirements/dev.txt
            python3 -m pip --version
            ls -lah ~/.cache/pip
      - save_cache:
          paths:
            - ".venv"
            - ".nox"
            - "~/.cache/pip"
          key: dependencies-20190912f
      - run:
          name: Run the nox gauntlet
          command: |
            . .venv/bin/activate
            python3 -m pip --version
            python3 -m pip freeze
            nox -l
            nox
