version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-20190909b
      - run:
          name: Prepare Python environment
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python -m pip install -q -U pip
            python -m pip install -q -r requirements/dev.txt
            python -m pip --version
      - save_cache:
          paths:
            - ".venv"
            - ".nox"
            - "~/.cache/pip"
          key: dependencies-20190909b
      - run:
          name: Install into updated environment
          command: |
            . .venv/bin/activate
            python -m pip --version
            python -m pip install -e .
      - run:
          name: Run nox
          command: |
            . .venv/bin/activate
            python -m pip --version
            python -m pip freeze
            nox -k -'not ensure' -l
            nox -k -'not ensure'
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Create .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: Deploy to PyPI
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            python -m pip install -r requirements/deploy.txt
            python -m pip install -e .
            python setup.py sdist bdist_wheel
            twine upload dist/*
